on:
  push:
    branches:
      - master
      - dev/version-checking

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Adjust version number in file name accordingly.
        if: steps.semantic.outputs.new_release_published == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo '{\n\t"version":"${{ steps.semantic.outputs.new_release_version }}",\n\t"changelog":"- ${{ steps.semantic.outputs.new_release_notes }}"\n} > ELS-FiveM/version.json' | git commit -a -m "dev!":" version update"
